# Generated by Django 5.0.1 on 2025-12-03 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STATUS_CHANGE', 'Status Changed'), ('ASSIGN', 'Assigned'), ('COMMENT', 'Commented'), ('ATTACH', 'Attached File')], max_length=20)),
                ('entity_type', models.CharField(choices=[('PROJECT', 'Project'), ('TASK', 'Task'), ('COMMENT', 'Comment')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('entity_name', models.CharField(max_length=200)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('organization_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UPDATED', 'Task Updated'), ('TASK_COMMENTED', 'Task Comment'), ('PROJECT_ASSIGNED', 'Added to Project'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_COMMENTED', 'Project Comment'), ('MENTION', 'Mentioned'), ('DEADLINE', 'Deadline Reminder')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
